apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backpressures.policy.openservicemesh.io
spec:
  group: policy.openservicemesh.io
  version: v1alpha1
  names:
    kind: Backpressure
    plural: backpressures
    singular: backpressure
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            maxConnections:
              description: "Maximum number of connections"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
            maxRequests:
              description: "Maximum number of parallel requests"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
            maxPendingRequests:
              description: "Max number of pending requests"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
            maxRetries:
              description: "Max number of parallel retries"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
            maxConnectionPools:
              description: "Maximum number of connection pools per cluster"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
